version: 2
jobs:
  markdown-spell-check:
    docker:
#    - image: jimmysong/website-builder:2019-07-18
#    - image: registry.gitlab.com/pipeline-components/markdownlint:latest
    - image: circleci/ruby
    working_directory: ~/site
    steps:
    - checkout
    - run:
        name: Running markdown spell check
        command: gem install mdl  &&  scripts/mdspell-check.sh
  markdown-style-check:
    docker:
    - image: circleci/ruby
    working_directory: ~/site
    steps:
    - checkout
    - run:
        name: Running markdown style check
        command:  gem install mdl && scripts/mdl-check.sh
workflows:
  version: 2
  workflow:
    jobs:
    #- lint-site
    - markdown-spell-check
    - markdown-style-check
